# This workflow will install Python dependencies, run tests and flake8 across
# platforms and python versions. 

name: ElliptiCBn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        python-version: ['3.9', '3.10' , '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install ElliptiCBn
      run: |
        # platform specific packages
        python -m pip install . pyproject.toml

    - name: run flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: run pytest coverage 
      run: |
        pip install pytest
        pytest tests/
